-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 13:52:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Skelp-zsp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Skelp-zsp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sklepp` DEFAULT CHARACTER SET utf8 ;
USE `Sklepp` ;

-- -----------------------------------------------------
-- Table `Skelp-zsp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sklepp`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `admin` INT NULL,
  `orders_id` INT NOT NULL,
  PRIMARY KEY (`id`, `orders_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skelp-zsp`.`offerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sklepp`.`offerts` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  CONSTRAINT `fk_offerts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Sklepp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skelp-zsp`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sklepp`.`orders` (
  `users_id` INT NOT NULL,
  `users_orders_id` INT NOT NULL,
  `offerts_id` INT NOT NULL,
  `offerts_users_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `users_orders_id`, `offerts_id`, `offerts_users_id`),
  CONSTRAINT `fk_users_has_offerts_users1`
    FOREIGN KEY (`users_id` , `users_orders_id`)
    REFERENCES `Sklepp`.`users` (`id` , `orders_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_offerts_offerts1`
    FOREIGN KEY (`offerts_id` , `offerts_users_id`)
    REFERENCES `Sklepp`.`offerts` (`id` , `users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
